version: "3.9"

services:
  web:
    build:
      context: .
    container_name: t3-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env # <--- this loads the env file
    environment:
      - DATABASE_URL # <--- this passes it into the container
    depends_on:
      - db

  db:
    image: postgres
    container_name: t3-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t3db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
