import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ThemeProvider } from "next-themes";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { SocketProvider } from "@/context/SocketProvider";

export const metadata: Metadata = {
  title: "Smart Study",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <SocketProvider>
        <html
          suppressHydrationWarning
          lang="en"
          className={`${GeistSans.variable}`}
        >
          <body>
            {/* It’s a good idea to add the attribute prop so that theme changes are handled via a CSS class */}
            <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
              <TRPCReactProvider>
                {/* <Navbar /> */}
                {children}</TRPCReactProvider>
              <Toaster />
            </ThemeProvider>
          </body>
        </html>
      </SocketProvider>
    </ClerkProvider>
  );
}
