import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { SocketProvider } from "@/context/SocketProvider";

export const metadata: Metadata = {
  title: "Smart Study",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <SocketProvider>
        <html suppressHydrationWarning lang="en" className={`${GeistSans.variable}`}>
          <body>
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster />

          </body>
        </html>
      </SocketProvider>

    </ClerkProvider>

  );
}
