export const data = [
    { "id": 1, "title": "Data Structures & Algorithms (DSA)" },
    { "id": 2, "title": "Competitive Programming (CP)" },
    { "id": 3, "title": "C/C++ Programming" },
    { "id": 4, "title": "Java Programming" },
    { "id": 5, "title": "Python Programming" },
    { "id": 6, "title": "Machine Learning & Artificial Intelligence (AI)" },
    { "id": 7, "title": "Web Development" },
    { "id": 8, "title": "Mobile App Development" },
    { "id": 9, "title": "Data Science & Analytics" },
    { "id": 10, "title": "Cloud Computing" },
    { "id": 11, "title": "DevOps & CI/CD" },
    { "id": 12, "title": "Cybersecurity & Ethical Hacking" },
    { "id": 13, "title": "Blockchain & Cryptocurrency" },
    { "id": 14, "title": "Game Development & Design" },
    { "id": 15, "title": "Internet of Things (IoT) & Embedded Systems" },
    { "id": 16, "title": "Software Engineering & Design Patterns" },
    { "id": 17, "title": "Robotics & Automation" },
    { "id": 18, "title": "Virtual Reality (VR) & Augmented Reality (AR)" },
    { "id": 19, "title": "UI/UX Design & Product Design" },
    { "id": 20, "title": "Open Source Contribution & Community Involvement" },
    { "id": 21, "title": "Calculus" },
    { "id": 22, "title": "Linear Algebra" },
    { "id": 23, "title": "Discrete Mathematics" },
    { "id": 24, "title": "Statistics" },
    { "id": 25, "title": "Physics" },
    { "id": 26, "title": "Chemistry" },
    { "id": 27, "title": "Biology" },
    { "id": 28, "title": "Economics" },
    { "id": 29, "title": "Psychology" },
    { "id": 30, "title": "Sociology" },
    { "id": 31, "title": "Philosophy" },
    { "id": 32, "title": "English Literature" },
    { "id": 33, "title": "History" }
]
