export const data = [
    { id: 1, title: "Data Structures & Algorithms (DSA)" },
    { id: 2, title: "Competitive Programming (CP)" },
    { id: 3, title: "C Programming" },
    { id: 4, title: "C++ Programming" },
    { id: 5, title: "Java Programming" },
    { id: 6, title: "Python Programming" },
    { id: 7, title: "JavaScript Programming" },
    { id: 8, title: "Ruby Programming" },
    { id: 9, title: "PHP Programming" },
    { id: 10, title: "Swift Programming" },
    { id: 11, title: "Kotlin Programming" },
    { id: 12, title: "R Programming" },
    { id: 13, title: "Machine Learning & Artificial Intelligence (AI)" },
    { id: 14, title: "Web Development" },
    { id: 15, title: "Mobile App Development" },
    { id: 16, title: "Data Science & Analytics" },
    { id: 17, title: "Cloud Computing" },
    { id: 18, title: "DevOps & CI/CD" },
    { id: 19, title: "Cybersecurity & Ethical Hacking" },
    { id: 20, title: "Blockchain & Cryptocurrency" },
    { id: 21, title: "Game Development & Design" },
    { id: 22, title: "Internet of Things (IoT) & Embedded Systems" },
    { id: 23, title: "Software Engineering & Design Patterns" },
    { id: 24, title: "Robotics & Automation" },
    { id: 25, title: "Virtual Reality (VR) & Augmented Reality (AR)" },
    { id: 26, title: "UI/UX Design & Product Design" },
    { id: 27, title: "Open Source Contribution & Community Involvement" },
    { id: 28, title: "Calculus" },
    { id: 29, title: "Linear Algebra" },
    { id: 30, title: "Discrete Mathematics" },
    { id: 31, title: "Statistics" },
    { id: 32, title: "Physics" },
    { id: 33, title: "Chemistry" },
    { id: 34, title: "Biology" },
    { id: 35, title: "Economics" },
    { id: 36, title: "Psychology" },
    { id: 37, title: "Sociology" },
    { id: 38, title: "Philosophy" },
    { id: 39, title: "English Literature" },
    { id: 40, title: "History" },
    { id: 41, title: "Formal Languages & Automata Theory (FLA)" },
    { id: 42, title: "Compiler Design" },
    { id: 43, title: "Computer Organization & Architecture (COA)" },
    { id: 44, title: "Computer Networks (CN)" },
    { id: 45, title: "Database Management Systems (DBMS)" },
    { id: 46, title: "Operating Systems (OS)" },
    { id: 47, title: "Software Testing & Quality Assurance" },
    { id: 48, title: "System Design & Architecture" },
    // Additional B.Tech related subjects
    { id: 49, title: "Simple Mathematics" },
    { id: 50, title: "Digital Logic Design" },
    { id: 51, title: "Signals & Systems" },
    { id: 52, title: "Control Systems" },
    { id: 53, title: "Microprocessors & Microcontrollers" },
    { id: 54, title: "Basic Electronics & Instrumentation" },
    { id: 55, title: "Engineering Mechanics" },
    { id: 56, title: "Electrical Machines" },
    { id: 57, title: "Environmental Studies" },
    { id: 58, title: "Computer Graphics" }
];
